package admin;

import javax.swing.JOptionPane;
import Login_Register.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;

public class Dashboard_admin extends javax.swing.JFrame {
    String username_pengguna;
    String fullname_pengguna;
    String status_penukaran = "";
    public Dashboard_admin(String username, String fullname) {
        initComponents();
        username_pengguna = username;
        fullname_pengguna = fullname;
        isi_riwayat_sampah();
        isi_riwayat_poin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        penukaransampah_name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_pengaturan = new javax.swing.JLabel();
        penukaranpoin_name = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logout_name = new javax.swing.JLabel();
        dashboard_name1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        judul_halaman = new javax.swing.JLabel();
        judul_halaman1 = new javax.swing.JLabel();
        judul_halaman2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        penukaranpoin_field = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        penukaransampah_field = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 600));

        jPanel1.setBackground(new java.awt.Color(80, 98, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Lemon", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 204, 27));
        jLabel6.setText("ECO PEDULI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logoEco_kecil.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard_menu.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/poin_menu.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        penukaransampah_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        penukaransampah_name.setForeground(new java.awt.Color(255, 255, 255));
        penukaransampah_name.setText("Penukaran Sampah");
        penukaransampah_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penukaransampah_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penukaransampah_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penukaransampah_nameMouseExited(evt);
            }
        });
        jPanel1.add(penukaransampah_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/jadwal_menu.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        label_pengaturan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        label_pengaturan.setText("Pengaturan Akun");
        jPanel1.add(label_pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        penukaranpoin_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        penukaranpoin_name.setForeground(new java.awt.Color(255, 255, 255));
        penukaranpoin_name.setText("Penukaran Poin");
        penukaranpoin_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseExited(evt);
            }
        });
        jPanel1.add(penukaranpoin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout_menu.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        logout_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout_name.setForeground(new java.awt.Color(255, 255, 255));
        logout_name.setText("Logout");
        logout_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_nameMouseExited(evt);
            }
        });
        jPanel1.add(logout_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        dashboard_name1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dashboard_name1.setForeground(new java.awt.Color(255, 255, 255));
        dashboard_name1.setText("Dashboard");
        dashboard_name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseExited(evt);
            }
        });
        jPanel1.add(dashboard_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul_halaman.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        judul_halaman.setForeground(new java.awt.Color(120, 148, 97));
        judul_halaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_halaman.setText("LIST PENUKARAN PENGGUNA");
        jPanel5.add(judul_halaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 670, -1));

        judul_halaman1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        judul_halaman1.setForeground(new java.awt.Color(241, 204, 27));
        judul_halaman1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_halaman1.setText("LIST PENUKARAN SAMPAH");
        jPanel5.add(judul_halaman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 260, -1));

        judul_halaman2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        judul_halaman2.setForeground(new java.awt.Color(255, 51, 51));
        judul_halaman2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_halaman2.setText("LIST PENUKARAN POIN");
        jPanel5.add(judul_halaman2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 220, -1));

        penukaranpoin_field.setEditable(false);
        penukaranpoin_field.setColumns(20);
        penukaranpoin_field.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        penukaranpoin_field.setRows(5);
        penukaranpoin_field.setFocusable(false);
        jScrollPane2.setViewportView(penukaranpoin_field);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 300, 350));

        penukaransampah_field.setEditable(false);
        penukaransampah_field.setColumns(20);
        penukaransampah_field.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        penukaransampah_field.setRows(5);
        penukaransampah_field.setFocusable(false);
        jScrollPane3.setViewportView(penukaransampah_field);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 300, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void isi_riwayat_sampah(){
        // deklarasi variabel
        String isi_riwayat = "";
        String SUrl, SUser, SPass, query;

        // Persiapan database, ganti nama db
        SUrl = "jdbc:MySQL://localhost:3306/db_pengguna_banksampah";
        SUser = "root";
        SPass = "";
        try{
            // menghubungkan ke database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            ResultSet rs;
            
            // mengisi kode unik
            query = "SELECT * FROM tb_penukaran_sampah WHERE status_penukaran = 'Belum'";
            rs = st.executeQuery(query);
            
            while(rs.next()){
                isi_riwayat = isi_riwayat + "id:\t" + rs.getString("id") + "\n";
                isi_riwayat = isi_riwayat + "username:\t" + rs.getString("username_pengguna") + "\n";
                isi_riwayat = isi_riwayat + "status:\t" + rs.getString("status_penukaran") + "\n\n";
            }
            
            System.out.println(isi_riwayat);
            if("".equals(isi_riwayat)){
                penukaransampah_field.setText("Tidak ada penukaran!");
            } else{
                penukaransampah_field.setText(isi_riwayat);
            }
            
        } catch(Exception e){
            System.out.println("Error!" + e.getMessage());
        }
    }
    
    private void isi_riwayat_poin(){
        // deklarasi variabel
        String isi_riwayat = "";
        String SUrl, SUser, SPass, query;

        // Persiapan database, ganti nama db
        SUrl = "jdbc:MySQL://localhost:3306/db_pengguna_banksampah";
        SUser = "root";
        SPass = "";
        try{
            // menghubungkan ke database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            ResultSet rs;
            
            // mengisi kode unik
            query = "SELECT * FROM tb_penukaran_barang WHERE status_pengambilan = 'Belum'";
            rs = st.executeQuery(query);
            
            while(rs.next()){
                isi_riwayat = isi_riwayat + "id_unik:\t" + rs.getString("id_unik") + "\n";
                isi_riwayat = isi_riwayat + "username:\t" + rs.getString("username_pengguna") + "\n";
                isi_riwayat = isi_riwayat + "status:\t" + rs.getString("status_pengambilan") + "\n\n";
            }
            
            System.out.println(isi_riwayat);
            if("".equals(isi_riwayat)){
                penukaranpoin_field.setText("Tidak ada penukaran!");
            } else{
                penukaranpoin_field.setText(isi_riwayat);
            }
            
        } catch(Exception e){
            System.out.println("Error!" + e.getMessage());
        }
    }
    
    private void logout_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseClicked
        int answer = JOptionPane.showConfirmDialog(null, "Apakah anda ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(answer==0){
            dispose();
            Login LoginPage = new Login();
            LoginPage.setVisible(true);
            LoginPage.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_logout_nameMouseClicked

    private void logout_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseEntered
        logout_name.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_logout_nameMouseEntered

    private void logout_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseExited
        logout_name.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_logout_nameMouseExited

    private void dashboard_name1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseEntered
        dashboard_name1.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_dashboard_name1MouseEntered

    private void dashboard_name1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseExited
        dashboard_name1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_dashboard_name1MouseExited

    private void penukaransampah_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaransampah_nameMouseEntered
        penukaransampah_name.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_penukaransampah_nameMouseEntered

    private void penukaransampah_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaransampah_nameMouseExited
        penukaransampah_name.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_penukaransampah_nameMouseExited

    private void penukaranpoin_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseEntered
        penukaranpoin_name.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_penukaranpoin_nameMouseEntered

    private void penukaranpoin_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseExited
        penukaranpoin_name.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_penukaranpoin_nameMouseExited

    private void dashboard_name1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseClicked
        dispose();
        Dashboard_admin dashboardPage = new Dashboard_admin(username_pengguna, fullname_pengguna);
        dashboardPage.setVisible(true);
        dashboardPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_dashboard_name1MouseClicked

    private void penukaransampah_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaransampah_nameMouseClicked
        dispose();
        penukaran_sampah penukaranPage = new penukaran_sampah(username_pengguna, fullname_pengguna);
        penukaranPage.setVisible(true);
        penukaranPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_penukaransampah_nameMouseClicked

    private void penukaranpoin_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseClicked
        dispose();
        penukaran_poin jadwalPage = new penukaran_poin(username_pengguna, fullname_pengguna);
        jadwalPage.setVisible(true);
        jadwalPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_penukaranpoin_nameMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboard_name1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel judul_halaman;
    private javax.swing.JLabel judul_halaman1;
    private javax.swing.JLabel judul_halaman2;
    private javax.swing.JLabel label_pengaturan;
    private javax.swing.JLabel logout_name;
    private javax.swing.JTextArea penukaranpoin_field;
    private javax.swing.JLabel penukaranpoin_name;
    private javax.swing.JTextArea penukaransampah_field;
    private javax.swing.JLabel penukaransampah_name;
    // End of variables declaration//GEN-END:variables
}
