package admin;

import javax.swing.JOptionPane;
import Login_Register.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;


public class penukaran_sampah extends javax.swing.JFrame {
    String username_pengguna;
    String fullname_pengguna;
    String status_penukaran = "";
    String poin = "";
    String username_tambahan = "";
    public penukaran_sampah(String username, String fullname) {
        initComponents();
        username_pengguna = username;
        fullname_pengguna = fullname;
        munculkan_konfirmasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        penukaransampah_name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_pengaturan = new javax.swing.JLabel();
        penukaranpoin_name = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logout_name = new javax.swing.JLabel();
        dashboard_name1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        judul_halaman = new javax.swing.JLabel();
        kodeunik_label = new javax.swing.JLabel();
        idpenukaran_field = new javax.swing.JTextField();
        cari_button = new javax.swing.JButton();
        konfirmasi_button = new javax.swing.JButton();
        username_label = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        status_label = new javax.swing.JLabel();
        status_field = new javax.swing.JTextField();
        listbarang_label = new javax.swing.JLabel();
        poinberat_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(80, 98, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Lemon", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 204, 27));
        jLabel6.setText("ECO PEDULI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logoEco_kecil.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard_menu.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/poin_menu.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        penukaransampah_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        penukaransampah_name.setForeground(new java.awt.Color(255, 255, 255));
        penukaransampah_name.setText("Penukaran Sampah");
        penukaransampah_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penukaransampah_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penukaransampah_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penukaransampah_nameMouseExited(evt);
            }
        });
        jPanel1.add(penukaransampah_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/jadwal_menu.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        label_pengaturan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        label_pengaturan.setText("Pengaturan Akun");
        jPanel1.add(label_pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        penukaranpoin_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        penukaranpoin_name.setForeground(new java.awt.Color(255, 255, 255));
        penukaranpoin_name.setText("Penukaran Poin");
        penukaranpoin_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseExited(evt);
            }
        });
        jPanel1.add(penukaranpoin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout_menu.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        logout_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout_name.setForeground(new java.awt.Color(255, 255, 255));
        logout_name.setText("Logout");
        logout_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_nameMouseExited(evt);
            }
        });
        jPanel1.add(logout_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        dashboard_name1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dashboard_name1.setForeground(new java.awt.Color(255, 255, 255));
        dashboard_name1.setText("Dashboard");
        dashboard_name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseExited(evt);
            }
        });
        jPanel1.add(dashboard_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul_halaman.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        judul_halaman.setForeground(new java.awt.Color(120, 148, 97));
        judul_halaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_halaman.setText("PENCARIAN DATA PENUKARAN SAMPAH");
        jPanel5.add(judul_halaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 630, -1));

        kodeunik_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        kodeunik_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kodeunik_label.setText("Masukkan ID Penukaran");
        jPanel5.add(kodeunik_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, -1));

        idpenukaran_field.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idpenukaran_field.setForeground(new java.awt.Color(102, 102, 102));
        idpenukaran_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idpenukaran_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpenukaran_fieldActionPerformed(evt);
            }
        });
        jPanel5.add(idpenukaran_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 280, 40));

        cari_button.setBackground(new java.awt.Color(120, 148, 97));
        cari_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cari_button.setForeground(new java.awt.Color(255, 255, 255));
        cari_button.setText("CARI DATA!");
        cari_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_buttonActionPerformed(evt);
            }
        });
        jPanel5.add(cari_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 260, 40));

        konfirmasi_button.setBackground(new java.awt.Color(120, 148, 97));
        konfirmasi_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        konfirmasi_button.setForeground(new java.awt.Color(255, 255, 255));
        konfirmasi_button.setText("KONFIRMASI STATUS");
        konfirmasi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasi_buttonActionPerformed(evt);
            }
        });
        jPanel5.add(konfirmasi_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 260, 50));

        username_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        username_label.setText("Username");
        jPanel5.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        username_field.setEditable(false);
        username_field.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        username_field.setForeground(new java.awt.Color(102, 102, 102));
        username_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        jPanel5.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, 40));

        status_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        status_label.setText("Status");
        jPanel5.add(status_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        status_field.setEditable(false);
        status_field.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        status_field.setForeground(new java.awt.Color(102, 102, 102));
        status_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_fieldActionPerformed(evt);
            }
        });
        jPanel5.add(status_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 190, 40));

        listbarang_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        listbarang_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listbarang_label.setText("POIN TAMBAHAN DAN BERAT TOTAL");
        jPanel5.add(listbarang_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 410, 570, -1));

        poinberat_field.setEditable(false);
        poinberat_field.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        poinberat_field.setForeground(new java.awt.Color(102, 102, 102));
        poinberat_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        poinberat_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinberat_fieldActionPerformed(evt);
            }
        });
        jPanel5.add(poinberat_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 570, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void munculkan_konfirmasi(){
        status_penukaran = status_field.getText();
        if("".equals(status_penukaran) || "Sudah".equals(status_penukaran)){
            konfirmasi_button.setVisible(false);
        } else{
            konfirmasi_button.setVisible(true);
        }
    }

    private void logout_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseClicked
        int answer = JOptionPane.showConfirmDialog(null, "Apakah anda ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(answer==0){
            dispose();
            Login LoginPage = new Login();
            LoginPage.setVisible(true);
            LoginPage.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_logout_nameMouseClicked

    private void logout_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseEntered
        logout_name.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_logout_nameMouseEntered

    private void logout_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseExited
        logout_name.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_logout_nameMouseExited

    private void dashboard_name1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseEntered
        dashboard_name1.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_dashboard_name1MouseEntered

    private void dashboard_name1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseExited
        dashboard_name1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_dashboard_name1MouseExited

    private void penukaransampah_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaransampah_nameMouseEntered
        penukaransampah_name.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_penukaransampah_nameMouseEntered

    private void penukaransampah_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaransampah_nameMouseExited
        penukaransampah_name.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_penukaransampah_nameMouseExited

    private void penukaranpoin_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseEntered
        penukaranpoin_name.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_penukaranpoin_nameMouseEntered

    private void penukaranpoin_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseExited
        penukaranpoin_name.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_penukaranpoin_nameMouseExited

    private void dashboard_name1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseClicked
        dispose();
        Dashboard_admin dashboardPage = new Dashboard_admin(username_pengguna, fullname_pengguna);
        dashboardPage.setVisible(true);
        dashboardPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_dashboard_name1MouseClicked

    private void penukaransampah_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaransampah_nameMouseClicked
        dispose();
        penukaran_sampah penukaranPage = new penukaran_sampah(username_pengguna, fullname_pengguna);
        penukaranPage.setVisible(true);
        penukaranPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_penukaransampah_nameMouseClicked

    private void penukaranpoin_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseClicked
        dispose();
        penukaran_poin jadwalPage = new penukaran_poin(username_pengguna, fullname_pengguna);
        jadwalPage.setVisible(true);
        jadwalPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_penukaranpoin_nameMouseClicked

    private void idpenukaran_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpenukaran_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpenukaran_fieldActionPerformed

    private void cari_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_buttonActionPerformed
        // deklarasi variabel
        String username="", poin_dan_berat="", id="";
        String SUrl, SUser, SPass, query;
        int found = 0;

        // Persiapan database, ganti nama db
        SUrl = "jdbc:MySQL://localhost:3306/db_pengguna_banksampah";
        SUser = "root";
        SPass = "";

        try{
            // menghubungkan ke database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            ResultSet rs;

            // Mengisi variabel
            id = idpenukaran_field.getText();

            // Mengambil data sesuai id unik
            query = "SELECT * FROM tb_penukaran_sampah WHERE id = '"+id+"' ";
            rs = st.executeQuery(query);

            while(rs.next()){
                username = rs.getString("username_pengguna");
                poin = rs.getString("poin_tambahan");
                poin_dan_berat = poin + " PTS && " + rs.getString("berat_total") + " KG";
                status_penukaran = rs.getString("status_penukaran");
                found = 1;
            }
            
            // mengisi variabel global username
            username_tambahan = username;
            
            // jika tidak ketemu keluarkan pesan error
            if(found == 0){
                JOptionPane.showMessageDialog(new JFrame(), "Kode Unik Salah!", "Error",
                    JOptionPane.ERROR_MESSAGE);
                idpenukaran_field.setText(" ");
                username_field.setText(" ");
                poinberat_field.setText(" ");
                status_field.setText(" ");
                status_penukaran = "";
            } else{
                username_field.setText(username);
                poinberat_field.setText(poin_dan_berat);
                status_field.setText(status_penukaran);
                if(status_penukaran.equals("Belum")){
                    status_field.setForeground(Color.red);
                } else{
                    status_field.setForeground(Color.green);
                }
            }
        } catch (Exception e){
            System.out.println("Error!" + e.getMessage());
        }

        // Menghilangkan atau memunculkan button konfirmasi
        if("".equals(status_penukaran) || "Sudah".equals(status_penukaran)){
            konfirmasi_button.setVisible(false);
        } else{
            konfirmasi_button.setVisible(true);
        }
    }//GEN-LAST:event_cari_buttonActionPerformed

    private void konfirmasi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasi_buttonActionPerformed
        int answer = JOptionPane.showConfirmDialog(null, "Apakah anda ingin mengonfirmasi data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(answer == 0){
            // deklarasi variabel
            String SUrl, SUser, SPass, query;

            // Persiapan database, ganti nama db
            SUrl = "jdbc:MySQL://localhost:3306/db_pengguna_banksampah";
            SUser = "root";
            SPass = "";

            try{
                // menghubungkan ke database
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
                Statement st = con.createStatement();

                // Mengupdate status dari belum menjadi sudah
                query = "UPDATE tb_penukaran_sampah SET status_penukaran = 'Sudah' WHERE id= '"+idpenukaran_field.getText()+"' ";
                st.execute(query);
                
                // Mengupdate poin pengguna
                query = "UPDATE tb_pengguna SET poin_pengguna = poin_pengguna + "+ Integer.parseInt(poin) + " WHERE username_pengguna = '"
                        + username_tambahan + "' ";
                st.execute(query);
                
                showMessageDialog(null, "Berhasil Menukarkan Sampah!");
                
                // Mengubah warna menjadi hijau
                status_field.setText("Sudah");
                status_field.setForeground(Color.green);
                munculkan_konfirmasi();
            } catch (Exception e){
                System.out.println("Error!" + e.getMessage());
            }
        }

    }//GEN-LAST:event_konfirmasi_buttonActionPerformed

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void status_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_fieldActionPerformed

    private void poinberat_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinberat_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poinberat_fieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari_button;
    private javax.swing.JLabel dashboard_name1;
    private javax.swing.JTextField idpenukaran_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel judul_halaman;
    private javax.swing.JLabel kodeunik_label;
    private javax.swing.JButton konfirmasi_button;
    private javax.swing.JLabel label_pengaturan;
    private javax.swing.JLabel listbarang_label;
    private javax.swing.JLabel logout_name;
    private javax.swing.JLabel penukaranpoin_name;
    private javax.swing.JLabel penukaransampah_name;
    private javax.swing.JTextField poinberat_field;
    private javax.swing.JTextField status_field;
    private javax.swing.JLabel status_label;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
