package operator;

import admin.*;
import javax.swing.JOptionPane;
import Login_Register.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;

public class penukaran_operator extends javax.swing.JFrame {
    String username_pengguna;
    String fullname_pengguna;
    String tipe_sampah;
    int poin_tambahan = 0, berat_total = 0;
    
    public penukaran_operator(String username, String fullname) {
        initComponents();
        username_pengguna = username;
        fullname_pengguna = fullname;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        penukaranpoin_name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_pengaturan = new javax.swing.JLabel();
        jadwal_name1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logout_name = new javax.swing.JLabel();
        dashboard_name1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label_utama = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        totalpoin_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatan_field = new javax.swing.JTextArea();
        catatan_label = new javax.swing.JLabel();
        tambah_button = new javax.swing.JButton();
        totalpenukaran_field = new javax.swing.JSpinner();
        totalpenukaran_label = new javax.swing.JLabel();
        tipesampah_field = new javax.swing.JComboBox<>();
        tipesampah_label = new javax.swing.JLabel();
        totalpoin_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(80, 98, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Lemon", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 204, 27));
        jLabel6.setText("ECO PEDULI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logoEco_kecil.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard_menu.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/poin_menu.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        penukaranpoin_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        penukaranpoin_name.setForeground(new java.awt.Color(255, 255, 255));
        penukaranpoin_name.setText("Penukaran Sampah");
        penukaranpoin_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penukaranpoin_nameMouseExited(evt);
            }
        });
        jPanel1.add(penukaranpoin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/jadwal_menu.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        label_pengaturan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        label_pengaturan.setText("Pengaturan Akun");
        jPanel1.add(label_pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        jadwal_name1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jadwal_name1.setForeground(new java.awt.Color(255, 255, 255));
        jadwal_name1.setText("Jadwal Pengambilan Sampah");
        jadwal_name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadwal_name1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jadwal_name1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jadwal_name1MouseExited(evt);
            }
        });
        jPanel1.add(jadwal_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout_menu.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        logout_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout_name.setForeground(new java.awt.Color(255, 255, 255));
        logout_name.setText("Logout");
        logout_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_nameMouseExited(evt);
            }
        });
        jPanel1.add(logout_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        dashboard_name1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dashboard_name1.setForeground(new java.awt.Color(255, 255, 255));
        dashboard_name1.setText("Dashboard");
        dashboard_name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboard_name1MouseExited(evt);
            }
        });
        jPanel1.add(dashboard_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_utama.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        label_utama.setText("TAMBAH POIN PENGGUNA");
        jPanel2.add(label_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        username_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        username_label.setText("Username");
        jPanel2.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        username_field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username_field.setForeground(new java.awt.Color(102, 102, 102));
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 510, 40));

        totalpoin_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        totalpoin_label.setText("Total Poin");
        jPanel2.add(totalpoin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        catatan_field.setColumns(20);
        catatan_field.setRows(5);
        jScrollPane1.setViewportView(catatan_field);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 250, 100));

        catatan_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        catatan_label.setText("Catatan");
        jPanel2.add(catatan_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        tambah_button.setBackground(new java.awt.Color(120, 148, 97));
        tambah_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tambah_button.setForeground(new java.awt.Color(255, 255, 255));
        tambah_button.setText("Tambah Poin!");
        tambah_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(tambah_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 210, 50));

        totalpenukaran_field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalpenukaran_field.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        totalpenukaran_field.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                totalpenukaran_fieldStateChanged(evt);
            }
        });
        jPanel2.add(totalpenukaran_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 200, 40));

        totalpenukaran_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        totalpenukaran_label.setText("Total Penukaran (Kg)");
        jPanel2.add(totalpenukaran_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        tipesampah_field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipesampah_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Pilih Tipe Sampah]", "Plastik", "Kaleng" }));
        tipesampah_field.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipesampah_fieldItemStateChanged(evt);
            }
        });
        tipesampah_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipesampah_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(tipesampah_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, 40));

        tipesampah_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tipesampah_label.setText("Tipe Sampah");
        jPanel2.add(tipesampah_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        totalpoin_field.setEditable(false);
        totalpoin_field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalpoin_field.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(totalpoin_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static boolean isNumber(String num){
        try{
            Integer.parseInt(num);
            return true;
        } catch(Exception e){
            return false;
        }
    }
    
    private void update_field_poin(){
        tipe_sampah = tipesampah_field.getSelectedItem().toString();
        berat_total = (int) totalpenukaran_field.getValue();
        if(tipe_sampah.equals("Plastik")){
            poin_tambahan = 100*berat_total;
        } else if (tipe_sampah.equals("Kaleng")){
            poin_tambahan = 200*berat_total;
        } else{
            poin_tambahan = 0;
        }
        totalpoin_field.setText(Integer.toString(poin_tambahan));
    }
    
    private void logout_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseClicked
        int answer = JOptionPane.showConfirmDialog(null, "Apakah anda ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(answer==0){
            dispose();
            Login LoginPage = new Login();
            LoginPage.setVisible(true);
            LoginPage.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_logout_nameMouseClicked

    private void logout_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseEntered
        logout_name.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_logout_nameMouseEntered

    private void logout_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_nameMouseExited
        logout_name.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_logout_nameMouseExited

    private void dashboard_name1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseEntered
        dashboard_name1.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_dashboard_name1MouseEntered

    private void dashboard_name1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseExited
        dashboard_name1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_dashboard_name1MouseExited

    private void penukaranpoin_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseEntered
        penukaranpoin_name.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_penukaranpoin_nameMouseEntered

    private void penukaranpoin_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseExited
        penukaranpoin_name.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_penukaranpoin_nameMouseExited

    private void jadwal_name1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwal_name1MouseEntered
        jadwal_name1.setForeground(new java.awt.Color(30, 30, 123));
    }//GEN-LAST:event_jadwal_name1MouseEntered

    private void jadwal_name1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwal_name1MouseExited
        jadwal_name1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jadwal_name1MouseExited

    private void dashboard_name1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_name1MouseClicked
        dispose();
        Dashboard_operator dashboardPage = new Dashboard_operator(username_pengguna, fullname_pengguna);
        dashboardPage.setVisible(true);
        dashboardPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_dashboard_name1MouseClicked

    private void penukaranpoin_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penukaranpoin_nameMouseClicked
        dispose();
        penukaran_operator penukaranPage = new penukaran_operator(username_pengguna, fullname_pengguna);
        penukaranPage.setVisible(true);
        penukaranPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_penukaranpoin_nameMouseClicked

    private void jadwal_name1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwal_name1MouseClicked
        dispose();
        jadwal_operator jadwalPage = new jadwal_operator(username_pengguna, fullname_pengguna);
        jadwalPage.setVisible(true);
        jadwalPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_jadwal_name1MouseClicked

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void tambah_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_buttonActionPerformed
        int answer = JOptionPane.showConfirmDialog(null, "Apakah anda ingin memberikan poin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(answer == 0){
            // deklarasi variabel
            String username = "", catatan = "", query;
            String SUrl, SUser, SPass;
            tipe_sampah = "";
            berat_total = 0;

            // Persiapan database, ganti nama db
            SUrl = "jdbc:MySQL://localhost:3306/db_pengguna_banksampah";
            SUser = "root";
            SPass = "";

            try{
                // menghubungkan ke database
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
                Statement st = con.createStatement();

                // membaca beberapa field
                username = username_field.getText();
                tipe_sampah = tipesampah_field.getSelectedItem().toString();
                berat_total = (int) totalpenukaran_field.getValue();
                catatan = catatan_field.getText();
                if(tipe_sampah.equals("Plastik")){
                    poin_tambahan = 100*berat_total;
                } else if(tipe_sampah.equals("Kaleng")){
                    poin_tambahan = 200*berat_total;
                } else{
                    poin_tambahan = 0;
                }

                if("".equals(username_field.getText())){ // jika username kosong
                    JOptionPane.showMessageDialog(new JFrame(), "Username Tidak Boleh Kosong", "Error",
                            JOptionPane.ERROR_MESSAGE);
                } else if(poin_tambahan == 0){ // jika poin kosong
                    JOptionPane.showMessageDialog(new JFrame(), "Poin Diperlukan", "Error",
                            JOptionPane.ERROR_MESSAGE);
                } else if(berat_total == 0){ // jika berat kosong
                    JOptionPane.showMessageDialog(new JFrame(), "Banyak Sampah Diperlukan", "Error",
                            JOptionPane.ERROR_MESSAGE);
                } else if(poin_tambahan < 0 || berat_total < 0 ){
                    JOptionPane.showMessageDialog(new JFrame(), "Poin atau berat harus valid!", "Error",
                            JOptionPane.ERROR_MESSAGE);
                } else{
                    // buat query untuk mengecek apakah username ada
                    query = "SELECT * FROM tb_pengguna WHERE username_pengguna = '"+username+"' ";

                    // cek apakah di database ada hasilnya
                    int Found = 0;
                    ResultSet rs = st.executeQuery(query);
                    while(rs.next()){
                        Found = 1;
                    }

                    // jika tidak ada usernamenya, maka pesan error
                    if(Found == 0){
                        JOptionPane.showMessageDialog(new JFrame(), "Username yang dimasukkan tidak ada!", "Error",
                            JOptionPane.ERROR_MESSAGE);
                    } else{
                        // Mencoba print hasil masukan dari user
                        System.out.println("username pengguna: " + username);
                        System.out.println(berat_total);
                        System.out.println(poin_tambahan);
                        System.out.println(catatan);

                        // Masukkan seluruh data ke tabel penukaran atau databse
                        query = "INSERT INTO tb_penukaran_sampah(username_pengguna, poin_tambahan, berat_total, catatan) VALUES ('"
                                + username + "', "+poin_tambahan+", "+berat_total+", '"+
                                catatan+"') ";
                        st.execute(query);

                        // Perbarui data poin pada tabel pengguna (Ubah ke halaman admin untuk di acc)
//                        query = "UPDATE tb_pengguna SET poin_pengguna = poin_pengguna + " + poin_tambahan
//                                + " WHERE username_pengguna = '" + username + "' ";
//                        st.execute(query);

                        showMessageDialog(null, "Berhasil Menambahkan Poin!");
                        showMessageDialog(null, "Silahkan Hubungi Admin Untuk Diapprove!");
                        
                        // set default
                        username_field.setText(" ");
                        catatan_field.setText(" ");
                        totalpenukaran_field.setValue(0);
                        totalpoin_field.setText("0");
                    }
                }
            } catch (Exception e){
                System.out.println("Error!" + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_tambah_buttonActionPerformed

    private void tipesampah_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipesampah_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipesampah_fieldActionPerformed

    private void tipesampah_fieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipesampah_fieldItemStateChanged
        update_field_poin();
    }//GEN-LAST:event_tipesampah_fieldItemStateChanged

    private void totalpenukaran_fieldStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_totalpenukaran_fieldStateChanged
        update_field_poin();
    }//GEN-LAST:event_totalpenukaran_fieldStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea catatan_field;
    private javax.swing.JLabel catatan_label;
    private javax.swing.JLabel dashboard_name1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jadwal_name1;
    private javax.swing.JLabel label_pengaturan;
    private javax.swing.JLabel label_utama;
    private javax.swing.JLabel logout_name;
    private javax.swing.JLabel penukaranpoin_name;
    private javax.swing.JButton tambah_button;
    private javax.swing.JComboBox<String> tipesampah_field;
    private javax.swing.JLabel tipesampah_label;
    private javax.swing.JSpinner totalpenukaran_field;
    private javax.swing.JLabel totalpenukaran_label;
    private javax.swing.JTextField totalpoin_field;
    private javax.swing.JLabel totalpoin_label;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
